### DISCUSSION TITLE
Theme not being applied in Github Actions

### DISCUSSION THREAD

**Discussion by samuelwine** [statiqdev/Discussions#188] [General]
I have this YML file
```
name: Statiq Web Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  DOTNET_VERSION: '7.0.x'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages    
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  
        uses: actions/checkout@v3
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2  

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Website
        run: dotnet run -p ./StatiqTryout/StatiqTryout.csproj

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload output only
          path: './StatiqTryout/output/posts'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

and using the CleanBlog theme, added as a submodule alongside the input folder.

When I run the app locally, the files in the output/posts folder have the theme applied. However when running this YML file in Github Actions, it seems to ignore the theme, and creates the output files with no modifications at all.

Is anyone able to point out what I am missing?

Many thanks!
