### DISCUSSION TITLE
Porting legacy Frontmatter with FrontMatterRegexes?

### DISCUSSION THREAD

**Discussion by bellons91** [statiqdev/Discussions#192] [Q&A]
I'm porting my GatsbyJS blog to Statiq.Web.

All my article (~130) have the frontmatter set such as:

```yml
---
title: "How to customize Conventional Commits in a .NET application using GitHooks"
path: "/blog/conventional-commit-with-githooks"
tags: ["dotNET", "npm", "MainArticle"]
featuredImage: "./cover.png"
excerpt: "Using Conventional Commits you can define a set of rules useful for writing meaningful commit messages. Using NPM. Yes, in a dotNET application!"
created: 2023-02-07
updated: 2023-02-07
---
```

Since some of those section names are not supported, I have to write a custom FrontMatterRegexes - I suppose.

Where can I find some documentation and some examples?

The documentation does not provide any example

> You can also customize the front matter styles using the following settings:
> 
> FrontMatterRegexes: Defines the default set of regular expressions used for identifying front matter. Changing this setting will overwrite the defaults above.
> AdditionalFrontMatterRegexes: Defines additional regular expressions used for identifying front matter in addition to the defaults described above.

Any idea?
