### DISCUSSION TITLE
How retrieve a complex setting

### DISCUSSION THREAD

**Discussion by Burgyn** [statiqdev/Discussions#22] [Q&A] [answered]
Hi,
in first step thanks for this great framework.

I'm trying to create docs generator for our microservice system.
My question is:
How can I retrieve a complex setting?

```yml
microservices:
  repositoryPath: '../../../GitHub/Sample.ApiGatewayOcelot/src/**/*.csproj'
  projectNamesPattern: 'MMLib.{*}.csproj'
```

I want group settings, but I don't know how to retrieve that.
