### DISCUSSION TITLE
Using appsettings.json for different environments

### DISCUSSION THREAD

**Discussion by suchja** [statiqdev/Discussions#222] [Q&A]
Most likely this is not a specific question about statiq, but I searched for hours without any success.

I would like to have settings like `Host` and `LinkRoot` only specified for the production environment (e.g. GitHub Pages). When running statiq's preview server, it should just work out of the box on localhost without any specific `LinkRoot`.
So I created this `appsettings.json`:
```json
{
    "Host": "",
    "LinkRoot": "",
    "LinksUseHttps": false
}
```

as well as an `appsettings.Production.json`
```json
{
    "Host": "suchja.github.io/",
    "LinkRoot": "/statiq-dopetrope-demo",
    "LinksUseHttps": true
}
```

Additionally I do have a `settings.yml` with some generic definitions (that I couldn't get into the `appsettings.json` - especially the calculated `PageTitle`):
```yml
SiteTitle: Dopetrope (Statiq)
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => "No Copyright"
PostSources: posts/**/*
IsPost: => Context.Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
PageSources: pages/**/*
IsPage: => Context.Outputs.FilterSources(Context.GetString("PageSources")).ContainsById(Document)
Layout: /_layout.cshtml
```

However, when I run `dotnet run --environment Production` the content from `appsettings.Production.json` seems not to be used, because the links in `index.html` do not change.
