### DISCUSSION TITLE
Pipeline deploy does not exist

### DISCUSSION THREAD

**Discussion by TheBrambleShark** [statiqdev/Discussions#39] [Q&A]
Versions:
Statiq.Razor: 1.0.0-beta.32
Statiq.Sass: 1.0.0-beta.32
Statiq.Web: 1.0.0-beta.18

I am in the process of setting up my site to be deployed through GitHub Actions. I have the following file named `deploy.yml`:

```yml
name: Deploy Site
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet run -l Debug -- deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
On execution, this results in an error message: `[CRIT] Pipeline deploy does not exist`.
Running without debug mode just says `[CRIT] Not found`.

## Things I have tried

* `Bootstrapper.AddPipeline<Statiq.Web.Pipelines.Deployment>()` in Program.cs
* Calling `DeployToGithupPages` instead of letting it figure it out from my settings.yml
* Specifically calling `deployment` instead of `deploy` in the Action.

All three exhibit the same behavior as above.

Program.cs:
```cs
public class Program
{
    public static async Task<int> Main(string[] args)
        => await Bootstrapper
        .Factory
        .CreateWeb(args)
        .RunAsync();
}
```
settings.yml:
```yml
Host: www.luzfaltex.com
LinksUseHttps: true
MirrorResources: true
EditLink: => "https://github.com/LuzFaltex/luzfaltex.github.io/edit/main/input/" + doc.Source.GetRelativeInputPath()
GitHubOwner: LuzFaltex
GitHubName: luzfaltex.github.io
GitHubToken: => Config.FromSetting<string>("GITHUB_TOKEN")
```
As far as I can tell, everything is correct here. In fact, beyond turning on debug mode and changing the github repository information, everything here is exactly the same as the version running the statiq.dev website. 

If any other files are needed, you can review my dev repository here: https://github.com/Foxtrek64/luzfaltex.github.io

When building locally, it appears to find the pipeline because I instead get an error saying it couldn't find the github token, which is to be expected. When running in Discord Actions however, it for some reason will consistently fail to find the deploy task.

Is this error message masking a different error? Or perhaps is there an issue with the Action environment?
